name: Unzip

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.zip'
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip the script.
        run: |
          ZIP_FILE=$(find . -name "*.zip" -print -quit)
          if [ -n "$ZIP_FILE" ]; then
            echo "Unzipping $ZIP_FILE"
            7z x "$ZIP_FILE" -o. -aoa
            rm "$ZIP_FILE"
          else
            echo "No zip file found."
          fi

      - name: Commit to repo.
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Unzipped files" || true
          git push
