name: Run server

on:
  workflow_dispatch:
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Unzip the script.
        run: |
          cd entityx-test
          chmod 777 ballisticakit_server
          chmod 777 dist/ballisticakit_headless
          ./ballisticakit_server
